task :build do
  version_rb = File.expand_path("../lib/example/version.rb", __FILE__)
  puts "Generating #{version_rb}"
  version = ENV["SPEC_VERSION"]
  version = "0.1.0" if version.to_s.empty?
  File.write(version_rb, <<-EOF)
 #:nodoc:
 module Example
  VERSION = "#{version}"
 end
  EOF
end

require "bundler/gem_tasks"
