# frozen_string_literal: true

task :build do
  platform_rb = File.expand_path("lib/speaker/platform.rb", __dir__)
  puts "Generating #{platform_rb}"

  if RUBY_PLATFORM == "java"
    File.write(platform_rb, <<-EOF)
 module Speaker
  #:nodoc:
  module Platform
    def self.name
      "Java"
    end
  end
 end
    EOF
  else
    File.write(platform_rb, <<-EOF)
 module Speaker
  #:nodoc:
  module Platform
    def self.name
      "Ruby"
    end
  end
 end
    EOF
  end

  version_rb = File.expand_path("lib/speaker/version.rb", __dir__)
  puts "Generating #{version_rb}"
  version = ENV["SPEC_VERSION"]
  version = "0.1.0" if version.to_s.empty?
  File.write(version_rb, <<-EOF)
 #:nodoc:
 module Speaker
   VERSION = "#{version}"
 end
  EOF
end

require "bundler/gem_tasks"
