task :build do
  platform_rb = File.expand_path("../lib/speaker/platform.rb", __FILE__)
  puts "Generating #{platform_rb}"

  if RUBY_PLATFORM == "java"
    File.write(platform_rb, <<-EOF)
module Speaker
  #:nodoc:
  module Platform
    def self.name
      "Java"
    end
  end
end
    EOF
  else
    File.write(platform_rb, <<-EOF)
module Speaker
  #:nodoc:
  module Platform
    def self.name
      "Ruby"
    end
  end
end
    EOF
  end
end

require "bundler/gem_tasks"
